version: 0.2

env:
  shell: bash
  variables:
    # For Docker
    DOCKER_BUILDKIT: 1
    COMPOSE_DOCKER_CLI_BUILD: 1
  secrets-manager:
    # API secrets
    APT_API_CONFIG: api-staging

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - TAG=v$APT_VERSION-staging
      - IFS="." read -r V_MAJOR V_MINOR V_PATCH <<< $APT_VERSION
      # set filewatcher limits
      - sysctl -w fs.inotify.max_user_watches=524288
      - sysctl -p
      # setup yarn
      - npm i -g yarn
      - echo Installing dependencies...
      # put our deployment key in the proper folder
      - cp $CODEBUILD_SRC_DIR_github_deployment_key_bundle/id_rsa ~/.ssh/id_rsa
      # export it for use
      - APT_SSH_KEY=`cat ~/.ssh/id_rsa`
      - export APT_SSH_KEY
      # API
      - aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin 006592501465.dkr.ecr.eu-north-1.amazonaws.com
     
  pre_build:
    commands:
      # API
      - aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin 006592501465.dkr.ecr.eu-north-1.amazonaws.com
      - docker pull 006592501465.dkr.ecr.eu-north-1.amazonaws.com/api:staging || true
      - docker pull 006592501465.dkr.ecr.eu-north-1.amazonaws.com/api-apps:staging || true
      - docker pull 006592501465.dkr.ecr.eu-north-1.amazonaws.com/api-push:staging || true
      - docker pull 006592501465.dkr.ecr.eu-north-1.amazonaws.com/api-analytics:staging || true
      - docker pull 006592501465.dkr.ecr.eu-north-1.amazonaws.com/api-build:staging || true
      - docker pull 006592501465.dkr.ecr.eu-north-1.amazonaws.com/api-pwa:staging || true
      - docker pull 006592501465.dkr.ecr.eu-north-1.amazonaws.com/api-cms-apps:staging || true
      - docker pull 006592501465.dkr.ecr.eu-north-1.amazonaws.com/api-webhook:staging || true
  build:
    commands:
      - echo Building...
      # build the API
      - cd $CODEBUILD_SRC_DIR_api_staging
      - docker-compose build --parallel api apps push analytics build pwa cms-apps webhook
      - docker tag api_api:latest 006592501465.dkr.ecr.eu-north-1.amazonaws.com/api:staging
      - docker tag api_apps:latest 006592501465.dkr.ecr.eu-north-1.amazonaws.com/api-apps:staging
      - docker tag api_push:latest 006592501465.dkr.ecr.eu-north-1.amazonaws.com/api-push:staging
      - docker tag api_analytics:latest 006592501465.dkr.ecr.eu-north-1.amazonaws.com/api-analytics:staging
      - docker tag api_build:latest 006592501465.dkr.ecr.eu-north-1.amazonaws.com/api-build:staging
      - docker tag api_pwa:latest 006592501465.dkr.ecr.eu-north-1.amazonaws.com/api-pwa:staging
      - docker tag api_cms_apps:latest 006592501465.dkr.ecr.eu-north-1.amazonaws.com/api-cms-apps:staging
      - docker tag api_webhook:latest 006592501465.dkr.ecr.eu-north-1.amazonaws.com/api-webhook:staging
     
  post_build:
    commands:
      # deploy API
      - echo API >> Updating environment...
      - cd $CODEBUILD_SRC_DIR_api_staging
      - docker push 006592501465.dkr.ecr.eu-north-1.amazonaws.com/api:staging
      - docker push 006592501465.dkr.ecr.eu-north-1.amazonaws.com/api-apps:staging
      - docker push 006592501465.dkr.ecr.eu-north-1.amazonaws.com/api-push:staging
      - docker push 006592501465.dkr.ecr.eu-north-1.amazonaws.com/api-analytics:staging
      - docker push 006592501465.dkr.ecr.eu-north-1.amazonaws.com/api-build:staging
      - docker push 006592501465.dkr.ecr.eu-north-1.amazonaws.com/api-pwa:staging
      - docker push 006592501465.dkr.ecr.eu-north-1.amazonaws.com/api-cms-apps:staging
      - docker push 006592501465.dkr.ecr.eu-north-1.amazonaws.com/api-webhook:staging
      - aws ecs update-service --cluster api-staging --service api --force-new-deployment
      - aws ecs update-service --cluster api-staging --service apps --force-new-deployment
      - aws ecs update-service --cluster api-staging --service push --force-new-deployment
      - aws ecs update-service --cluster api-staging --service analytics --force-new-deployment
      - aws ecs update-service --cluster api-staging --service build --force-new-deployment
      - aws ecs update-service --cluster api-staging --service pwa --force-new-deployment
      - aws ecs update-service --cluster api-staging --service cms-apps --force-new-deployment
      - aws ecs update-service --cluster api-staging --service webhook --force-new-deployment
     
artifacts:
  files:
    - 'build/*'
  base-directory: $CODEBUILD_SRC_DIR_cms_staging
  discard-paths: yes
  secondary-artifacts:
    api_staging:
      base-directory: $CODEBUILD_SRC_DIR_api_staging
      files:
        - api-staging
      name: api-staging
    github_deployment_key_bundle:
      base-directory: $CODEBUILD_SRC_DIR_github_deployment_key_bundle
      files:
        - github-deployment-key-bundle
      name: github-deployment-key-bundle
