name: Dev Auto-Deploy

on:
  push:
    pull_request:
    types: [ labeled ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-merge:
    if: ${{ github.event.label.name == 'staging' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Generate config file
      run: cp ./config/config.example.json ./config/config.json

    - name: Set env variable
      run: |
        echo 'APT_API_CONFIG<<EOF' >> $GITHUB_ENV
        echo `cat ./config/config.json` >> $GITHUB_ENV
        echo 'EOF' >> $GITHUB_ENV
    - name: Build whole project
      run: go build -v ./...

    - name: Generate test config file
      run: cp ./config/config_test.json ./config/config.json

    - name: Set env variable
      run: |
        echo 'APT_API_CONFIG<<EOF' >> $GITHUB_ENV
        echo `cat ./config/config.json` >> $GITHUB_ENV
        echo 'EOF' >> $GITHUB_ENV
        
    - name: Start docker container & Run test cases
      run: bash run_test_cases.sh

    - name: Stop docker container
      run: docker-compose down

  auto-bump:
    runs-on: ubuntu-latest
    needs: [ check-merge ]
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.APT_DEPLOYMENT_ACCESS_TOKEN }}

      - name: Auto-Bump & Tag
        run: bash .scripts/bump.sh
  trigger-deploy:
    runs-on: ubuntu-latest
    needs: [ check-merge, auto-bump ]
    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-north-1
    - name: Run CodeBuild
      uses: aws-actions/aws-codebuild-run-build@v1
      with:
        project-name: api-dev
        buildspec-override: .aws/buildspecs/buildspec_api_.yml
