# This is a basic workflow to help you get started with Actions

name: Release based-prod

on:
  release:
    types: [published]
    tags: 
      - v.*-prod

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  check-merge:
    if:  ${{ startsWith(github.event.release.tag_name, v.*-prod) }}
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.RN_APP_KEY }}

      - uses: actions/setup-node@v2
        with:
          node-version: 'lts/fermium'

      - name: Create test .env file
        run: cp .env.example .env

      - name: Install node modules
        run: yarn install
        
      - name: Lint JS/TS
        run: yarn lint:js

      - name: Run tests
        run: yarn test
  auto-bump:
    runs-on: ubuntu-latest
    needs: [ check-merge ]
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.APT_DEPLOYMENT_ACCESS_TOKEN }}

      - name: Auto-Bump & Tag
        run: bash .scripts/bump.sh
  trigger-deploy:
    runs-on: ubuntu-latest
    needs: [ check-merge, auto-bump ]
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1
      - name: Run CodeBuild
        uses: aws-actions/aws-codebuild-run-build@v1
        with:
          project-name: cms-prod
          buildspec-override: .aws/buildspecs/buildspec_prod.yml
